In [1]:
import pandas as pd
df=pd.read_csv('apt.csv',encoding='cp949')

In [2]:
df

,지역,번지,본번,부번,아파트,면적,계약년월,계약일,가격,층,건축년도,도로명
0,강원도 강릉시 견소동,202,202,0,송정한신,59.800,201910,4,10900,5,1997,경강로2539번길 8
1,강원도 강릉시 견소동,202,202,0,송정한신,116.175,201910,31,18500,10,1997,경강로2539번길 8
2,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.990,201910,5,25000,6,2005,경강로2539번길 22
3,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.990,201910,12,20600,3,2005,경강로2539번길 22
4,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.990,201910,20,20500,1,2005,경강로2539번길 22
...,...,...,...,...,...,...,...,...,...,...,...,...
42753,충청북도 충주시 호암동,547-6,547,6,호반현대,59.760,201910,29,7000,3,1994,신촌2길 28
42754,충청북도 충주시 호암동,221-23,221,23,호암리버빌(1단지),84.680,201910,5,12000,15,2002,원호암5길 32
42755,충청북도 충주시 호암동,221-23,221,23,호암리버빌(1단지),84.680,201910,15,11000,7,2002,원호암5길 32
42756,충청북도 충주시 호암동,221-23,221,23,호암리버빌(1단지),84.680,201910,17,12000,14,2002,원호암5길 32
42757,충청북도 충주시 호암동,221-23,221,23,호암리버빌(1단지),84.680,201910,26,11200,11,2002,원호암5길 32

In [8]:
df.지역.str.find('강릉')

0        4
1        4
2        4
3        4
4        4
        ..
42753   -1
42754   -1
42755   -1
42756   -1
42757   -1
Name: 지역, Length: 42758, dtype: int64

In [19]:
df[df.지역.str.find('강릉')>-1] #지역에 강릉이 들어간 자료만 출력

,지역,번지,본번,부번,아파트,면적,계약년월,계약일,가격,층,건축년도,도로명
0,강원도 강릉시 견소동,202,202,0,송정한신,59.8000,201910,4,10900,5,1997,경강로2539번길 8
1,강원도 강릉시 견소동,202,202,0,송정한신,116.1750,201910,31,18500,10,1997,경강로2539번길 8
2,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,5,25000,6,2005,경강로2539번길 22
3,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,12,20600,3,2005,경강로2539번길 22
4,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,20,20500,1,2005,경강로2539번길 22
...,...,...,...,...,...,...,...,...,...,...,...,...
183,강원도 강릉시 회산동,608,608,0,강릉서희스타힐스리버파크,84.8956,201910,24,24000,10,2017,회산로 344
184,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,84.9925,201910,7,24000,3,2018,회산로383번길 37
185,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9974,201910,19,23000,15,2018,회산로383번길 37
186,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9985,201910,21,24100,6,2018,회산로383번길 37
187,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9974,201910,29,25400,13,2018,회산로383번길 37

In [18]:
df[(df.지역.str.find('안양동안구')>-1) & (df.가격>90000)]
#지역이 안양동안구 중에서 가격이 9억 이상인 데이터 출력

,지역,번지,본번,부번,아파트,면적,계약년월,계약일,가격,층,건축년도,도로명
8257,경기도 안양동안구 관양동,1669,1669,0,동편마을(4단지),135.510,201910,2,112800,8,2012,동편로 135
8259,경기도 안양동안구 관양동,1669,1669,0,동편마을(4단지),120.660,201910,13,109300,15,2012,동편로 135
8260,경기도 안양동안구 관양동,1669,1669,0,동편마을(4단지),120.660,201910,16,98000,2,2012,동편로 135
8493,경기도 안양동안구 평촌동,Jan-75,75,1,평촌 이편한세상,157.931,201910,16,105800,7,2010,흥안대로456번길 17
8494,경기도 안양동안구 평촌동,Jan-75,75,1,평촌 이편한세상,130.628,201910,29,114000,15,2010,흥안대로456번길 17
8518,경기도 안양동안구 호계동,1054-6,1054,6,목련두산,101.940,201910,19,92500,6,1993,평촌대로179번길 27
8519,경기도 안양동안구 호계동,1054-6,1054,6,목련두산,101.940,201910,22,92000,7,1993,평촌대로179번길 27
8531,경기도 안양동안구 호계동,1054-8,1054,8,목련우성7,133.740,201910,14,99000,8,1992,귀인로 157

In [21]:
dfF=df[df.지역.str.find('강릉')>-1] #지역에 강릉이 들어간 자료만 출력
dfF.mean()

본번               inf
부번      1.085106e+00
면적      7.047780e+01
계약년월    2.019100e+05
계약일     1.527128e+01
가격      1.541457e+04
층       7.420213e+00
건축년도    2.000463e+03
dtype: float64

In [22]:
dfF

,지역,번지,본번,부번,아파트,면적,계약년월,계약일,가격,층,건축년도,도로명
0,강원도 강릉시 견소동,202,202,0,송정한신,59.8000,201910,4,10900,5,1997,경강로2539번길 8
1,강원도 강릉시 견소동,202,202,0,송정한신,116.1750,201910,31,18500,10,1997,경강로2539번길 8
2,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,5,25000,6,2005,경강로2539번길 22
3,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,12,20600,3,2005,경강로2539번길 22
4,강원도 강릉시 견소동,289,289,0,송정해변신도브래뉴아파트,84.9900,201910,20,20500,1,2005,경강로2539번길 22
...,...,...,...,...,...,...,...,...,...,...,...,...
183,강원도 강릉시 회산동,608,608,0,강릉서희스타힐스리버파크,84.8956,201910,24,24000,10,2017,회산로 344
184,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,84.9925,201910,7,24000,3,2018,회산로383번길 37
185,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9974,201910,19,23000,15,2018,회산로383번길 37
186,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9985,201910,21,24100,6,2018,회산로383번길 37
187,강원도 강릉시 회산동,130,130,0,힐스테이트 강릉,74.9974,201910,29,25400,13,2018,회산로383번길 37